[package]
name = 'lox_rs'
version = '0.1.0'
authors = ['IceSentry <c.giguere42@gmail.com>']
edition = '2018'

[dependencies]
derive-new = '0.5.8'
float-cmp = '0.6.0'
structopt = "0.3.12"
enum_dispatch = "0.2.3"
